openapi: 3.0.1
info:
  title: Health Check API with function logging Documentation
  description: This Application monitors the health of the application and logs how
    many times the healthCheck function is invoked
  contact:
    name: Ravi
    url: https://www.fairdeal.market/
    email: ravi@fairdeal.market
  license:
    name: FairDeal 2.0
    url: https://www.fairdeal.market/
  version: v1.0
externalDocs:
  description: Spring Boot Health Check Api documentation
  url: https://www.fairdeal.market/
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: Health Check APIs for Monitoring Health
  description: "Create User, Update User, Get User, Get All Users, Delete User"
paths:
  /health:
    get:
      tags:
      - Health Check APIs for Monitoring Health
      summary: Check the health of the Application
      description: Check health API is used to retrieve current Health status of the
        Application
      operationId: healthCheck
      responses:
        "200":
          description: "HTTP Status 200 ,Application is up and running"
          content:
            '*/*':
              schema:
                type: string
components: {}
